version: "3.9"
services:
  web:
    container_name: budal_web
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    networks:
      - bood4ll_laravel_network
    ports:
      - "80:8000"
      - "5173:5173"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./applications:/var/www
    environment:
      - APP_NAME=Bood4ll
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=15432
      - DB_DATABASE=db_bood4ll
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - MAIL_HOST=mailhog
      - MAIL_PORT=25
      - MAIL_FROM_ADDRESS="noreply@localhost"
      - MAIL_FROM_NAME="Bood4ll System"

    command: >
        bash -c "
          chmod -R 777 storage
          cp .env.example .env
          composer install
          php artisan key:generate
          php artisan migrate --seed
          npm install
          /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
        "
    depends_on:
      - postgres
  
  postgres:
    container_name: budal_postgres
    image: postgres:alpine
    restart: always
    networks:
      - bood4ll_laravel_network
    ports:
      - 15432:15432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_bood4ll
      # POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: admin
    command: -p 15432

  pgadmin:
    container_name: budal_pgadmin
    image: dpage/pgadmin4
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    restart: always  
    networks:
      - bood4ll_laravel_network
    ports:
      - "${PGADMIN_PORT:-5000}:80"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgadmin4/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    depends_on:
      - postgres

  mailhog:
    container_name: budal_mailhog
    image: mailhog/mailhog:latest
    entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]
    restart: always
    networks:
      - bood4ll_laravel_network
    ports:
      - 25:1025
      - 7000:8025
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:25

networks:
  bood4ll_laravel_network:
    driver: bridge
