version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - USER=${USER:-laravel}
        - APPDIR=${APPDIR:-/var/www}
    restart: always
    container_name: budal_web
    networks:
      - bood4ll_laravel_network
    ports:
      - "80:8000"
      - "5173:5173"
    volumes:
      - ./app:${APPDIR:-/var/www}
      - ./app/.env.example:${APPDIR:-/var/www}/.env
      - web-nodemodules-volume:${APPDIR:-/var/www}/node_modules
      - web-vendor-volume:${APPDIR:-/var/www}/vendor
    environment:
      - APP_NAME=${APP_NAME:-Bood4ll}

      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-db_bood4ll}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-admin}

      - CACHE_DRIVER=${CACHE_DRIVER:-redis}
      - SESSION_DRIVER=${SESSION_DRIVER:-redis}
      - SESSION_LIFETIME=${SESSION_LIFETIME:-120}

      - REDIS_HOST=${REDIS_HOST:-redis}
      # - REDIS_PASSWORD=${REDIS_PASSWORD:-null}
      - REDIS_PORT=${REDIS_PORT:-6379}

      - MAIL_HOST=${MAIL_HOST:-mailpit}
      - MAIL_PORT=${MAIL_PORT:-1025}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-"hello@example.com"}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-"Bood4ll"}

    depends_on:
      - postgres
  
  postgres:
    container_name: budal_postgres
    image: postgres:alpine
    restart: always
    networks:
      - bood4ll_laravel_network
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD-admin}
    command: -p ${DB_PORT:-5432}

  pgadmin:
    container_name: budal_pgadmin
    image: dpage/pgadmin4
    entrypoint: >
      /bin/sh -c "
        echo '
          {
            \"Servers\": {
              \"1\": {
                \"Name\": \"${APP_NAME:-Bood4ll}\",
                \"Group\": \"Servers\",
                \"Host\": \"${DB_HOST:-postgres}\",
                \"Port\": ${DB_PORT:-5432},
                \"MaintenanceDB\": \"postgres\",
                \"Username\": \"${DB_USERNAME:-postgres}\",
                \"PassFile\": \"/var/lib/pgadmin/pgpass\",
                \"SSLMode\": \"prefer\"
              }
            }
          }
        ' > /var/lib/pgadmin/servers;
        echo '${DB_HOST:-postgres}:${DB_PORT:-5432}:*:${DB_USERNAME:-postgres}:${DB_PASSWORD}' > /var/lib/pgadmin/pgpass;
        chmod 600 /var/lib/pgadmin/pgpass;
        chown pgadmin /var/lib/pgadmin/pgpass;
        /entrypoint.sh
      "
    restart: always  
    networks:
      - bood4ll_laravel_network
    ports:
      - ${PGADMIN_PORT:-5050}:80
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgadmin4/pgpass
      - pgadmin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER_JSON_FILE: '/var/lib/pgadmin/servers'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    depends_on:
      - postgres

  # pgadmin:
  #   container_name: budal_pgadmin
  #   image: dpage/pgadmin4
  #   entrypoint: >
  #     /bin/sh -c "
  #       cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
  #       chmod 600 /var/lib/pgadmin/pgpass;
  #       chown pgadmin:pgadmin /var/lib/pgadmin/pgpass;
  #       /entrypoint.sh
  #     "
  #   restart: always  
  #   networks:
  #     - bood4ll_laravel_network
  #   ports:
  #     - ${PGADMIN_PORT:-5050}:80
  #   volumes:
  #     - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
  #     - ./docker/pgadmin/pgpass:/pgadmin4/pgpass
  #     - pgadmin-volume:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_SERVER_JSON_FILE: '/var/lib/pgadmin/servers'
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #     PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
  #     GUNICORN_ACCESS_LOGFILE: '/dev/null'
  #   depends_on:
  #     - postgres

  redis:
    container_name: budal_redis
    image: redis:alpine
    restart: always
    networks:
      - bood4ll_laravel_network
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    volumes:
      - redis-volume:/data
    command: /bin/sh -c "redis-server --port ${REDIS_PORT:-6379}"
    # command: /bin/sh -c "redis-server --port ${REDIS_PORT:-6379} --requirepass ${REDIS_PASSWORD}"

  redis-commander:
    container_name: budal_redis-commander
    image: rediscommander/redis-commander
    restart: unless-stopped
    networks:
      - bood4ll_laravel_network
    ports:
      - ${REDIS_COMANDER_PORT:-6060}:8081
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis

  mailpit:
    container_name: budal_mailpit
    image: axllent/mailpit:latest
    # entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]
    restart: always
    networks:
      - bood4ll_laravel_network
    ports:
      - ${MAIL_PORT:-1025}:1025
      - ${MAILSERVER_PORT:-7070}:8025
    # environment:
    #   - MH_SMTP_BIND_ADDR=0.0.0.0:${MAIL_PORT:-1025}

networks:
  bood4ll_laravel_network:
    driver: bridge

volumes:
  web-nodemodules-volume:
  web-vendor-volume:
  postgres-volume:
  pgadmin-volume:
  redis-volume: